## imports and files

In [1]:
import pandas as pd
import os
import sys
from pprint import PrettyPrinter
pp = PrettyPrinter(indent=4)

# get an absolute path to the directory that contains parent files
__file__ = globals()['_dh'][0]
project_dir = __file__ = globals()['_dh'][0]
sys.path.append(os.path.normpath(os.path.join(
    project_dir, '..', '..', '..', '..')))

from experiments.utils.constants import (
    PIPELINE_PROFILING_RESULTS_PATH
)
from experiments.utils.parser import Parser

In [2]:
from json import load

series = 1
config_key_mapper = "key_config_mapper.csv"

series_path = os.path.join(
    PIPELINE_PROFILING_RESULTS_PATH,
    'series',
    str(series))

loader = Parser(
    series_path=series_path, config_key_mapper=config_key_mapper, model_name='video', type_of='pipeline')

In [3]:
configs = loader.load_configs()
for config_name, config in configs.items():
    print(f"File name: {config_name}")
    pp.pprint(config) 

File name: 0.yaml
{   'benchmark_duration': 1,
    'metadata': 'pipeline benchmarking',
    'mode': 'exponential',
    'nodes': [   {   'cpu_request': ['1', '2', '4'],
                     'data_type': 'image',
                     'max_batch_size': ['1', '4', '16'],
                     'max_batch_time': ['1'],
                     'memory_request': ['10Gi'],
                     'model_variants': ['yolov5n', 'yolov5s', 'yolov5m'],
                     'node_name': 'yolo',
                     'num_interop_threads': ['1'],
                     'num_threads': ['1'],
                     'replicas': [1, 2, 4],
                     'use_threading': 'True'},
                 {   'cpu_request': ['1', '2', '4'],
                     'data_type': 'text',
                     'max_batch_size': ['1', '4', '16'],
                     'max_batch_time': ['1'],
                     'memory_request': ['10Gi'],
                     'model_variants': ['resnet18', 'resnet34', 'resnet50'],
            

## config map reader

In [4]:
key_config_df = loader.key_config_mapper()
# display(key_config_df)
key_config_df.columns
results = loader.result_processing()

In [ ]:
for item in results.columns: print(item)

In [ ]:
experiment_results = loader.get_experiment_detail(2)
display(experiment_results)
# -------------------------
experiment_results.keys()
filenames = loader.get_result_file_names()
display(filenames)
# -------------------------
results = loader._read_results()
display(results.keys())
# -------------------------
flattened_results = loader.flatten_results(results['1']['responses'])
display(flattened_results)
# -------------------------
experiment_id = 1
flattened_results = loader.flatten_results(
    results[str(experiment_id)]['responses'])
latencies, timeout_count = loader.latency_calculator(
    flattened_results)
display(pd.DataFrame(latencies))
# -------------------------
results = loader.result_processing()
# print(results)
# print(list(results.columns))
for item in list(results.columns):
    if 'task_0' in item:
        print(item)
# -------------------------
for item in results.columns: print(item)
# -------------------------
experiment_id = 1
flattened_results = loader.flatten_results(
    results[str(experiment_id)]['responses'])
latencies, timeout_count = loader.latency_calculator(
    flattened_results)
display(pd.DataFrame(latencies))
# -------------------------
summary = loader.latency_summary(latencies=latencies)
pd.DataFrame(list(summary.items()))

In [7]:
key_config_df = loader.key_config_mapper()
print(key_config_df.columns)
# selected_key_config_df =  key_config_df[key_config_df['model_variant_1'] == 'yolov5n']
# selected_key_config_df
key_config_df

Index(['experiment_id', 'pipeline_name', 'load', 'load_duration', 'series',
       'metadata', 'mode', 'data_type', 'benchmark_duration',
       'task_0_node_name', 'task_0_model_variant', 'task_0_cpu_request',
       'task_0_memory_request', 'task_0_max_batch_size',
       'task_0_max_batch_time', 'task_0_replica', 'task_1_node_name',
       'task_1_model_variant', 'task_1_cpu_request', 'task_1_memory_request',
       'task_1_max_batch_size', 'task_1_max_batch_time', 'task_1_replica'],
      dtype='object')


experiment_id pipeline_name  load  load_duration  series  \
0                 1         video    10             60       1   
1                 2         video    30             60       1   
2                 3         video    10             60       1   
3                 4         video    30             60       1   
4                 5         video    10             60       1   
...             ...           ...   ...            ...     ...   
2403           2404         video    30             60       1   
2404           2405         video    10             60       1   
2405           2406         video    30             60       1   
2406           2407         video    10             60       1   
2407           2408         video    30             60       1   

                   metadata         mode data_type  benchmark_duration  \
0     pipeline benchmarking  exponential     image                   1   
1     pipeline benchmarking  exponential     image                   1   
2     pipeline benchmarking  exponential     image                   1   
3     pipeline benchmarking  exponential     image                   1   
4     pipeline benchmarking  exponential     image                   1   
...                     ...          ...       ...                 ...   
2403  pipeline benchmarking  exponential     image                   1   
2404  pipeline benchmarking  exponential     image                   1   
2405  pipeline benchmarking  exponential     image                   1   
2406  pipeline benchmarking  exponential     image                   1   
2407  pipeline benchmarking  exponential     image                   1   

     task_0_node_name  ... task_0_max_batch_size  task_0_max_batch_time  \
0                yolo  ...                     1                      1   
1                yolo  ...                     1                      1   
2                yolo  ...                     1                      1   
3                yolo  ...                     1                      1   
4                yolo  ...                     1                      1   
...               ...  ...                   ...                    ...   
2403             yolo  ...                     4                      1   
2404             yolo  ...                     4                      1   
2405             yolo  ...                     4                      1   
2406             yolo  ...                     4                      1   
2407             yolo  ...                     4                      1   

     task_0_replica  task_1_node_name  task_1_model_variant  \
0                 1      resnet-human              resnet18   
1                 1      resnet-human              resnet18   
2                 1      resnet-human              resnet18   
3                 1      resnet-human              resnet18   
4                 1      resnet-human              resnet18   
...             ...               ...                   ...   
2403              2      resnet-human              resnet34   
2404              2      resnet-human              resnet34   
2405              2      resnet-human              resnet34   
2406              4      resnet-human              resnet34   
2407              4      resnet-human              resnet34   

      task_1_cpu_request task_1_memory_request task_1_max_batch_size  \
0                      1                  10Gi                     1   
1                      1                  10Gi                     1   
2                      1                  10Gi                     1   
3                      1                  10Gi                     1   
4                      1                  10Gi                     1   
...                  ...                   ...                   ...   
2403                   2                  10Gi                    16   
2404                   2                  10Gi                    16   
2405              

In [ ]:
experiment_ids = key_config_df[
    key_config_df['load'] == 10][
    'experiment_id'].tolist()

metadata_columns = [
    'experiment_id',
    'task_0_cpu_request',
    'task_0_model_variant',
    'task_0_replica',
    'task_0_max_batch_size',
    'task_1_cpu_request',
    'task_1_model_variant',
    'task_1_replica',
    'task_1_max_batch_size',
    ]

selected_results_columns = [
    'client_to_pipeline_latencies_avg',
    'task_0_model_latencies_avg',
    'task_0_to_task_1_latencies_avg',
    'task_1_model_latencies_avg',
    ]


output = loader.table_maker(
    experiment_ids=experiment_ids,
    metadata_columns=metadata_columns,
    results_columns=selected_results_columns)
pd.set_option('display.max_rows', None)
output['model_latencies_sum'] = output['task_0_model_latencies_avg'] + output['task_1_model_latencies_avg']
output['e2e_latencies'] = output['task_0_model_latencies_avg'] + output['task_1_model_latencies_avg'] + output['task_0_to_task_1_latencies_avg']


In [12]:
display(output[output['task_0_to_task_1_latencies_avg']>0].sort_values(by=['model_latencies_sum'], ascending=False).head(10))

experiment_id  task_0_cpu_request task_0_model_variant  task_0_replica  \
647            1297                   1              yolov5n               1   
674            1351                   2              yolov5n               1   
1133           2269                   1              yolov5n               1   
893            1789                   1              yolov5n               2   
890            1783                   1              yolov5n               1   
944            1891                   4              yolov5n               1   
656            1315                   1              yolov5n               1   
920            1843                   2              yolov5n               2   
1160           2323                   2              yolov5n               1   
1139           2281                   1              yolov5n               4   

      task_0_max_batch_size  task_1_cpu_request task_1_model_variant  \
647                      16                   1             resnet18   
674                      16                   1             resnet18   
1133                      4                   1             resnet34   
893                       1                   1             resnet34   
890                       1                   1             resnet34   
944                       1                   1             resnet34   
656                      16                   2             resnet18   
920                       1                   1             resnet34   
1160                      4                   1             resnet34   
1139                      4                   1             resnet34   

      task_1_replica  task_1_max_batch_size  client_to_pipeline_latencies_avg  \
647                1                     16                          1.604137   
674                1                     16                          0.869397   
1133               1                     16                          1.069063   
893                1                     16                          0.796910   
890                1                     16                          1.068809   
944                1                     16                          0.868984   
656                1                     16                          1.424697   
920                1                     16                          0.782039   
1160               1                     16                          0.872003   
1139               1                     16                          1.150197   

      task_0_model_latencies_avg  task_0_to_task_1_latencies_avg  \
647                     1.089657                        0.280503   
674                     0.846809                        0.543723   
1133                    0.326425                        0.134049   
893                     0.090109                        0.072061   
890                     0.079850                        0.042715   
944                     0.049656                        0.069991   
656                     0.995049                        0.241991   
920                     0.075403                        0.095853   
1160                    0.223351                        0.126636   
1139                    0.284870                        0.267709   

      task_1_model_latencies_avg  model_latencies_sum  e2e_latencies  
647                     0.676306             1.765962       2.046466  
674                     0.698028             1.544837       2.088559  
1133                    1.056104             1.382529       1.516578  
893                     1.260967             1.351076       1.423137  
890                     1.269475             1.349325       1.392040  
944                     1.276840             1.326496       1.396487  
656                     0.320323             1.315371       1.557362  
920                     1.236779             1.312182       1.408036  
1160                    1.075114             1.29846

In [14]:
a = output[output['task_0_to_task_1_latencies_avg']>0].sort_values(by=['model_latencies_sum'], ascending=False).experiment_id.to_numpy()
a

array([1297, 1351, 2269, ...,  133,  151,  145])

In [15]:
b = output[output['task_0_to_task_1_latencies_avg']>0].sort_values(by=['e2e_latencies'], ascending=False).experiment_id.to_numpy()
b

array([1373, 1351, 1297, ...,  153,  147,  145])

In [16]:
a

array([1297, 1351, 2269, ...,  133,  151,  145])

In [17]:
b

array([1373, 1351, 1297, ...,  153,  147,  145])

In [28]:
sum(a == b)

5